// Package db provides database access for gitgres: repos, refs, and Git objects
// stored in PostgreSQL. Schema and queries are in sql/; Go code is generated by
// sqlc (see Queries, ListRefs, ObjectRead, etc.) plus hand-written connection and
// helpers.
//
// Library usage: open a pool with OpenPool, then create Queries with New(pool).
// Use GetOrCreateRepo or GetRepo to resolve a repo name to an ID. For a
// storage.Storer implementation that uses this package, see internal/storer.
package db
