// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Object struct {
	RepoID  int32  `json:"repo_id"`
	Oid     []byte `json:"oid"`
	Type    int16  `json:"type"`
	Size    int32  `json:"size"`
	Content []byte `json:"content"`
}

type Ref struct {
	RepoID   int32       `json:"repo_id"`
	Name     string      `json:"name"`
	Oid      []byte      `json:"oid"`
	Symbolic pgtype.Text `json:"symbolic"`
}

type Repository struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
