// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: objects.sql

package db

import (
	"context"
)

const listObjectOids = `-- name: ListObjectOids :many
SELECT oid FROM objects WHERE repo_id = $1
`

func (q *Queries) ListObjectOids(ctx context.Context, repoID int32) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listObjectOids, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var oid []byte
		if err := rows.Scan(&oid); err != nil {
			return nil, err
		}
		items = append(items, oid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectOidsCount = `-- name: ListObjectOidsCount :one
SELECT count(*)::int FROM objects WHERE repo_id = $1
`

func (q *Queries) ListObjectOidsCount(ctx context.Context, repoID int32) (int32, error) {
	row := q.db.QueryRow(ctx, listObjectOidsCount, repoID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const objectRead = `-- name: ObjectRead :one
SELECT type, size, content FROM objects WHERE repo_id = $1 AND oid = $2
`

type ObjectReadParams struct {
	RepoID int32  `json:"repo_id"`
	Oid    []byte `json:"oid"`
}

type ObjectReadRow struct {
	Type    int16  `json:"type"`
	Size    int32  `json:"size"`
	Content []byte `json:"content"`
}

func (q *Queries) ObjectRead(ctx context.Context, arg ObjectReadParams) (ObjectReadRow, error) {
	row := q.db.QueryRow(ctx, objectRead, arg.RepoID, arg.Oid)
	var i ObjectReadRow
	err := row.Scan(&i.Type, &i.Size, &i.Content)
	return i, err
}

const objectWrite = `-- name: ObjectWrite :one
SELECT git_object_write($1::integer, $2::smallint, $3) AS oid
`

type ObjectWriteParams struct {
	RepoID  int32       `json:"repo_id"`
	ObjType int16       `json:"obj_type"`
	Content interface{} `json:"content"`
}

func (q *Queries) ObjectWrite(ctx context.Context, arg ObjectWriteParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, objectWrite, arg.RepoID, arg.ObjType, arg.Content)
	var oid interface{}
	err := row.Scan(&oid)
	return oid, err
}
