// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRefs = `-- name: ListRefs :many
SELECT name, oid, symbolic FROM refs WHERE repo_id = $1 ORDER BY name
`

type ListRefsRow struct {
	Name     string      `json:"name"`
	Oid      []byte      `json:"oid"`
	Symbolic pgtype.Text `json:"symbolic"`
}

func (q *Queries) ListRefs(ctx context.Context, repoID int32) ([]ListRefsRow, error) {
	rows, err := q.db.Query(ctx, listRefs, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRefsRow{}
	for rows.Next() {
		var i ListRefsRow
		if err := rows.Scan(&i.Name, &i.Oid, &i.Symbolic); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefsCount = `-- name: ListRefsCount :one
SELECT count(*)::int FROM refs WHERE repo_id = $1
`

func (q *Queries) ListRefsCount(ctx context.Context, repoID int32) (int32, error) {
	row := q.db.QueryRow(ctx, listRefsCount, repoID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const refDelete = `-- name: RefDelete :exec
DELETE FROM refs WHERE repo_id = $1 AND name = $2
`

type RefDeleteParams struct {
	RepoID int32  `json:"repo_id"`
	Name   string `json:"name"`
}

func (q *Queries) RefDelete(ctx context.Context, arg RefDeleteParams) error {
	_, err := q.db.Exec(ctx, refDelete, arg.RepoID, arg.Name)
	return err
}

const refInsert = `-- name: RefInsert :exec

INSERT INTO refs (repo_id, name, oid)
VALUES ($1, $2, $3)
ON CONFLICT (repo_id, name) DO UPDATE SET oid = $3, symbolic = NULL
`

type RefInsertParams struct {
	RepoID int32  `json:"repo_id"`
	Name   string `json:"name"`
	Oid    []byte `json:"oid"`
}

// Remote-helper push: direct ref write/delete (no reflog, no CAS)
func (q *Queries) RefInsert(ctx context.Context, arg RefInsertParams) error {
	_, err := q.db.Exec(ctx, refInsert, arg.RepoID, arg.Name, arg.Oid)
	return err
}

const refInsertSymbolic = `-- name: RefInsertSymbolic :exec
INSERT INTO refs (repo_id, name, symbolic)
VALUES ($1, $2, $3)
ON CONFLICT (repo_id, name) DO UPDATE SET oid = NULL, symbolic = $3
`

type RefInsertSymbolicParams struct {
	RepoID   int32       `json:"repo_id"`
	Name     string      `json:"name"`
	Symbolic pgtype.Text `json:"symbolic"`
}

func (q *Queries) RefInsertSymbolic(ctx context.Context, arg RefInsertSymbolicParams) error {
	_, err := q.db.Exec(ctx, refInsertSymbolic, arg.RepoID, arg.Name, arg.Symbolic)
	return err
}

const refSetSymbolic = `-- name: RefSetSymbolic :exec
SELECT git_ref_set_symbolic($1::integer, $2::text, $3::text)
`

type RefSetSymbolicParams struct {
	RepoID int32  `json:"repo_id"`
	Name   string `json:"name"`
	Target string `json:"target"`
}

func (q *Queries) RefSetSymbolic(ctx context.Context, arg RefSetSymbolicParams) error {
	_, err := q.db.Exec(ctx, refSetSymbolic, arg.RepoID, arg.Name, arg.Target)
	return err
}

const refUpdate = `-- name: RefUpdate :one
SELECT git_ref_update(
    $1::integer,
    $2::text,
    $3,
    $4,
    $5::boolean
) AS ok
`

type RefUpdateParams struct {
	RepoID int32       `json:"repo_id"`
	Name   string      `json:"name"`
	NewOid interface{} `json:"new_oid"`
	OldOid interface{} `json:"old_oid"`
	Force  bool        `json:"force"`
}

func (q *Queries) RefUpdate(ctx context.Context, arg RefUpdateParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, refUpdate,
		arg.RepoID,
		arg.Name,
		arg.NewOid,
		arg.OldOid,
		arg.Force,
	)
	var ok interface{}
	err := row.Scan(&ok)
	return ok, err
}

const refsHasHEAD = `-- name: RefsHasHEAD :one
SELECT 1 FROM refs WHERE repo_id = $1 AND name = 'HEAD' ORDER BY repo_id LIMIT 1
`

func (q *Queries) RefsHasHEAD(ctx context.Context, repoID int32) (int32, error) {
	row := q.db.QueryRow(ctx, refsHasHEAD, repoID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
