// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package db

import (
	"context"
)

const getOrCreateRepo = `-- name: GetOrCreateRepo :one
INSERT INTO repositories (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = $1
RETURNING id
`

func (q *Queries) GetOrCreateRepo(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateRepo, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getRepo = `-- name: GetRepo :one
SELECT id FROM repositories WHERE name = $1
`

func (q *Queries) GetRepo(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, getRepo, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}
